---
- name: Include install tasks
  ansible.builtin.include_tasks: install.yml

- name: Include security tasks
  ansible.builtin.include_tasks: security.yml

- name: Include modules tasks
  ansible.builtin.include_tasks: modules.yml

- name: Include vhosts tasks
  ansible.builtin.include_tasks: vhosts.yml
