---
- name: Update apt cache.
  ansible.builtin.apt:
    update_cache: true
    cache_valid_time: 3600

- name: Install apache packages (Debian)
  ansible.builtin.package:
    name: "{{ apache_packages }}"
    state: present
  notify: Start apache on boot

- name: Set Apache port
  ansible.builtin.lineinfile:
    dest: "{{ apache_server_conf }}/ports.conf"
    regexp: "{{ item.regexp }}"
    line: "{{ item.line }}"
    state: present
  with_items: "{{ apache_ports_configuration_items }}"
  notify: Restart apache

- name: Update security.conf
  ansible.builtin.lineinfile:
    dest: "{{ apache_server_conf }}/conf-available/security.conf"
    regexp: "{{ item.regexp }}"
    line: "{{ item.line }}"
    state: present
  with_items: "{{ apache_security_configuration_items }}"
  notify: Restart apache

- name: Enable apache mods
  community.general.apache2_module:
    state: present
    name: "{{ item }}"
  loop: "{{ apache_mods_enabled }}"
  notify: Restart apache

- name: Disable apache mods
  community.general.apache2_module:
    state: absent
    name: "{{ item }}"
  loop: "{{ apache_mods_disabled }}"
  notify: Restart apache

- name: Add vhosts
  ansible.builtin.template:
    src: "vhosts.conf.j2"
    dest: "{{ apache_server_conf }}/sites-available/{{ apache_vhosts_filename }}"
    owner: root
    group: root
    mode: "0644"
  notify: Restart apache
  when: apache_create_vhosts

- name: Delete default vhosts in site-enabled
  ansible.builtin.file:
    path: "{{ apache_server_conf }}/sites-enabled/{{ item }}"
    state: absent
  with_items: "{{ apache_default_vhost_filename }}"
  notify: Restart apache
  when: apache_remove_default_vhost

- name: Vhost symlink in site-enabled
  ansible.builtin.file:
    src: "{{ apache_server_conf }}/sites-available/{{ apache_vhosts_filename }}"
    dest: "{{ apache_server_conf }}/sites-enabled/{{ apache_vhosts_filename }}"
    state: link
  notify: Restart apache
  when: apache_create_vhosts
