---
- name: Enable apache mods
  community.general.apache2_module:
    state: present
    name: "{{ item }}"
  loop: "{{ apache_mods_enabled }}"
  notify: Restart apache

- name: Disable apache mods
  community.general.apache2_module:
    state: absent
    name: "{{ item }}"
  loop: "{{ apache_mods_disabled }}"
  notify: Restart apache
